Ofvictor20200704
EngelFlores/controle-transacoes pull request #17
Opened 2020-07-04 16:54 UTC by ofvictor

Tive que mexer em classes de outras 3 entidades do modelo (TransactnioType, TransactnioChannel e CustomerAccount) para ajustar o relacionamento JPA entre estas e a TransactionAccount.

2020-07-04 23:21 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/domains/TransactionChannel.java
> +    public TransactionChannel() {
Não é necessário criar construtor vazio.

2020-07-04 23:22 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/domains/TransactionAccount.java
> +    public TransactionAccount() {
Não é necessário criar construtor vazio.

2020-07-04 23:22 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/domains/TransactionType.java
> +	public TransactionType() {
Não é necessário criar construtor vazio.

2020-07-04 23:22 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/requests/BankOperationRequest.java
> +	public BankOperationRequest() {
Não é necessário criar construtor vazio.

2020-07-04 23:23 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/requests/BankOperationRequest.java
> +	public BankOperationRequest() {
Não é necessário criar construtor vazio.

2020-07-04 23:27 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/domains/Customer.java
> +
A remoção do setId vai quebrar os teste de Customer.

2020-07-04 23:32 UTC, EngelFlores requested changes
Por favor, readicione o setId em Customer para não quebrar os testes e remova os construtores vazios que não possuem outro construtor. E a atualize a branch para resolver os conflitos.

2020-07-04 23:44 UTC, EngelFlores commented on src/main/java/com/acelera/tcc/group03/controllers/BankOperationController.java
> +    @GetMapping("/get-account-statement/{id}/{amount-of-days}")
Por favor, remova código comentado.

2020-07-05 18:45 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/domains/TransactionChannel.java
> +    public TransactionChannel() {
Ajustado.

2020-07-05 18:46 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/domains/TransactionType.java
> +	public TransactionType() {
Ajustado.

2020-07-05 18:49 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/domains/TransactionAccount.java
> +    public TransactionAccount() {
Ajustado.

2020-07-05 19:06 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/requests/BankOperationRequest.java
> +	public BankOperationRequest() {
Ajustado.

2020-07-06 02:37 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/domains/Customer.java
> +
Conforme já sinalizei e você já executou, o que precisa ser removido é o setId.

2020-07-06 02:38 UTC, ofvictor commented on src/main/java/com/acelera/tcc/group03/controllers/BankOperationController.java
> +    @GetMapping("/get-account-statement/{id}/{amount-of-days}")
A operação foi implementada.

2020-07-06 02:38 UTC, ofvictor commented
Favor revisar e aprovar, as 5 operações bancárias estão implementadas.

2020-07-06 03:18 UTC, EngelFlores approved these changes
Vamos precisar atualizar alguns testes depois dessas mudanças.

2020-07-06 03:18 UTC, merged