Customer
EngelFlores/controle-transacoes pull request #3
Opened 2020-03-08 19:41 UTC by EngelFlores

Adding customer controller and service, and some minor changes.

2020-03-09 12:17 UTC, santosglaiton approved these changes

2020-03-11 21:37 UTC, ofvictor requested changes
Olá Engel, faltou subir a classe CustomerRepository na PR, acredito que você tenha incluído a TransactionTypeRepository por engano no lugar dela. Por favor, revise.

2020-03-12 06:10 UTC, EngelFlores commented
> Olá Engel, faltou subir a classe CustomerRepository na PR, acredito que você tenha incluído a TransactionTypeRepository por engano no lugar dela. Por favor, revise.

A classe já está no projeto, só não aparece no PR porque está comparando com a master e nessa parte a minha branch não difere da master. O TransactionTypeRepository está na minha branch porque eu atualizei ela com a master, uma prática comum para evitar conflitos.

2020-03-12 12:55 UTC, ofvictor approved these changes

2020-03-12 12:55 UTC, merged